<?php

require_once('fpdf.php');

class PDF extends FPDF{
	
	protected $security;
	protected $user;
	function __construct($security, $user){
		parent::__construct();
		$this->security = $security;
		$this->user = $user;
	}
	function Header(){
		$this->SetY(5);
		$this->SetFont('Times', 'B', 20);
		$this->Cell(0,20,'Internal Services Report', 0, 2, 'C');
		$this->SetAlpha(0.1);
		$this->SetFont('Times', 'B', 100);
		if($this->security > 1){
			$this->TextWithRotation(45,200,'Confidential', 45);
		}else{
			$this->TextWithRotation(80,170,'Public',45);
		}
		$this->SetAlpha(1);
		$this->SetY(30);
	}
	function Footer(){
		$this->SetY(-15);
		$this->SetFont('Times', 'B', 8);
		$this->Cell(0, 5, 'Security: '.$this->security, 0, 2, 'R');
		$this->Cell(0, 5, 'Page '.$this->PageNo(), 0, 0, 'R');
		$this->SetY(-15);
		$this->Cell(0, 5, "Generated By: ".$this->user, 0, 2, 'L');
		$this->Cell(0, 5, date("Y/m/d H:i:s"), 0, 0, 'L');
	}
	// The following code is from http://www.fpdf.org/en/script/script74.php
	protected $extgstates = array();

	// alpha: real value from 0 (transparent) to 1 (opaque)
	// bm:	blend mode, one of the following:
	//		  Normal, Multiply, Screen, Overlay, Darken, Lighten, ColorDodge, ColorBurn,
	//		  HardLight, SoftLight, Difference, Exclusion, Hue, Saturation, Color, Luminosity
	function SetAlpha($alpha, $bm='Normal'){
		// set alpha for stroking (CA) and non-stroking (ca) operations
		$gs = $this->AddExtGState(array('ca'=>$alpha, 'CA'=>$alpha, 'BM'=>'/'.$bm));
		$this->SetExtGState($gs);
	}

	function AddExtGState($parms){
		$n = count($this->extgstates)+1;
		$this->extgstates[$n]['parms'] = $parms;
		return $n;
	}

	function SetExtGState($gs){
		$this->_out(sprintf('/GS%d gs', $gs));
	}

	function _enddoc(){
		if(!empty($this->extgstates) && $this->PDFVersion<'1.4')
			$this->PDFVersion='1.4';
		parent::_enddoc();
	}

	function _putextgstates(){
		for ($i = 1; $i <= count($this->extgstates); $i++)
		{
			$this->_newobj();
			$this->extgstates[$i]['n'] = $this->n;
			$this->_put('<</Type /ExtGState');
			$parms = $this->extgstates[$i]['parms'];
			$this->_put(sprintf('/ca %.3F', $parms['ca']));
			$this->_put(sprintf('/CA %.3F', $parms['CA']));
			$this->_put('/BM '.$parms['BM']);
			$this->_put('>>');
			$this->_put('endobj');
		}
	}

	function _putresourcedict(){
		parent::_putresourcedict();
		$this->_put('/ExtGState <<');
		foreach($this->extgstates as $k=>$extgstate)
			$this->_put('/GS'.$k.' '.$extgstate['n'].' 0 R');
		$this->_put('>>');
	}

	function _putresources(){
		$this->_putextgstates();
		parent::_putresources();
	}
	// This code is from http://www.fpdf.org/en/script/script31.php
	function TextWithRotation($x, $y, $txt, $txt_angle, $font_angle=0){
	$font_angle+=90+$txt_angle;
	$txt_angle*=M_PI/180;
	$font_angle*=M_PI/180;

	$txt_dx=cos($txt_angle);
	$txt_dy=sin($txt_angle);
	$font_dx=cos($font_angle);
	$font_dy=sin($font_angle);

	$s=sprintf('BT %.2F %.2F %.2F %.2F %.2F %.2F Tm (%s) Tj ET',$txt_dx,$txt_dy,$font_dx,$font_dy,$x*$this->k,($this->h-$y)*$this->k,$this->_escape($txt));
	if ($this->ColorFlag)
		$s='q '.$this->TextColor.' '.$s.' Q';
	$this->_out($s);
}
}

function generate_report($title, $security, $user, $body){
	$pdf = new PDF($security, $user);
	$pdf->AliasNbPages();
	$pdf->AddPage();
	$pdf->SetFont('Times', 'B', 20);
	$pdf->Cell(0,10,$title,0,0,'C');
	$pdf->Ln();
	$pdf->Ln();
	$pdf->SetFont('Times', 'B', 12);
	$pdf->Cell(0,10,$body,0,0,'C');
	return base64_encode($pdf->Output('S'));
}

?>
